version: 0.2
phases:
  install:
    commands:
    - echo "install step running on..."
    - echo "running commit $CODEBUILD_SOURCE_VERSION"
  pre_build:
    commands:
    - echo "pre_build step"
    - chmod +x gradlew
    - curl -sL https://deb.nodesource.com/setup_8.x | bash - && apt-get install -y nodejs
  build:
    commands:
    - ./gradlew build bundle
    - ls -lah
    - aws s3 sync --delete site/build/web ${S3_BUCKET}
    - aws s3 cp site/build/bundle/kesselringio.bundle.js ${S3_BUCKET}
  post_build:
    commands:
    - echo "post_build step"
    - printenv
    - |-
      curl -d "{\"text\": \"Just Build ${GITHUB_REPO_NAME}-${CODEBUILD_SOURCE_VERSION} triggered by ${CODEBUILD_INITIATOR} with Status: ${CODEBUILD_BUILD_SUCCEEDING}\"}" ${SLACK_WEBHOOK}
    - aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DISTRIBUTION_ID} --paths "/*"